apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<Your Account ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<Your Account ID>:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J3AWYQKNKW2I
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-21T02:37:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "841"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f7b13643-beec-42da-978b-ed107b03a7b3
